### ISSUE TITLE
Getting an error adding package in Xcode 11.4.1

### ISSUE THREAD

**Issue by derickito** [ScottORLY/Swawsh#2]
![image](https://user-images.githubusercontent.com/712249/80711197-931bae80-8ab5-11ea-9dd1-f610848bf8c5.png)

I'm getting the above error when adding your package

**Comment by scottorly** [comment]
Try setting the `Rules` option to `Branch: master`
<img width="486" alt="Screen Shot 2020-05-03 at 11 54 23 PM" src="https://user-images.githubusercontent.com/13109315/80942431-95be2280-8d99-11ea-8cfd-ec73aaf5e756.png">
